### ISSUE TITLE
Authentication prevented

### ISSUE THREAD

**Issue by TVLuke** [jaetzold/philips-hue-java-sdk#2]
Hi,

just started using your sdk, had slight problem with the authentication. since the boolean authenticated is set to true without actual checks in the methods authenticate(String, boolean)  and setUsername(String) 

I uncommented the lines 167 and  349 (in the current commit) and now it seems to work just fine.

Not sure if I missunderstood the usage or if this is a bug.

Cheers,
Lukas

**Comment by jaetzold** [comment]
What where your problems with the authentication? How did you use it and what was the observed behavior?
I'm a bit puzzled that uncommenting those lines helped you getting access to the bridge. So i would be very interested to hear more about how you used the library and what your problem was. :-)

To the lines you commented out: Both have in fact a check, but maybe not that obvious:

In line 167 authenticated is only ever set to _false_ because of the '&='. It is there to set authenticated to false if the username is changed. Because for a different username it is not assumed that the authentication is still valid.

In line 349 the authenticated is _only_ set to true if the method call just before did not produce an exception. In that case the user already is allowed to access the bridge and that is what authenticated==true actually means: The current username is allowed to access the bridge.
But depending on the exception there is probably not good coding style. It may be better to let completeSync return a boolean or guard the setting of authenticated with a check for "initialSyncDone".

**Comment by TVLuke** [comment]
I use a piece of code found in an example

```
        String username = "552627b33010930f275b72ab1c7be255";
        //http://192.168.1.102/
        InetAddress ip_of_hue = InetAddress.getByAddress(new byte[] {(byte)192,(byte)168,(byte)1,(byte)102});

        System.out.println("Connecting to "+ip_of_hue+" with username "+username);
        HueBridge bridge = new HueBridge(ip_of_hue, username);
        String username1 = bridge.getUsername();
        System.out.println(username1);
        bridge.authenticate(true);
        String username2 = bridge.getUsername();
        System.out.println(username2);

        Collection<HueLightBulb> lights = (Collection<HueLightBulb>) bridge.getLights();
```

The problem that occured without commenting out those lines was, that completeSync threw an error. This seemed to be due to the fact that even though the username was not authenticated the username was somehow set localy so in the method authenticate the check "if (equalEnough(usernameToTry, username))" returned true and thus authenticated was set to true. As a consequence the later check "if(!isAuthenticated())" retuns false and the 30 second waiting never happend, thuis never giving me the oportunity to actually authenticate the username. 

at the end of the authenticate method completeSync(username); is called which will then throw en exeption due to "throw new HueCommException(datastore.getJSONObject("error"));"

Commenting out those two lines allowed the 30 second waiting period to happen and I could authenticate the username. 

After that I found that I had to put them back in, otherwise I have to reauthenticate whith each restart of the aplication.

**Comment by jaetzold** [comment]
ok. Thanks for the description. I will try to reproduce that when I'm back at home.

**Comment by TVLuke** [comment]
OK, this issue should probably be deleted, since it was entirely my fault. I had gotten your code send from a friend and imported the code he send me (assuming he had just gotten it from here). What i did not know, he had played with the HueBridgeComm-Class a bit. So, now using your original source it works just fantastic. Thanks for the sdk!

**Comment by jaetzold** [comment]
Happy to hear, that it now works for you. :-)
